{% set name = "cacts" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cacts-{{ version }}.tar.gz
  sha256: 256b9d9c76959e74dfeee3aebdbe4368fef7e216d0a31427ee3e4a92d954f21e

build:
  entry_points:
    - cacts = cacts:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - psutil
    - pyyaml

test:
  imports:
    - cacts
  commands:
    - pip check
    - cacts --help
    - cacts --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/E3SM-Project/cacts
  summary: A framework for configurable unit testing of a cmake-based project
  license: BSD-3-Clause
  license_file: license

extra:
  recipe-maintainers:
    - mahf708
    - bartgol
    - xylar
