{% set name = "cacts" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cacts-{{ version }}.tar.gz
  sha256: c31f677a40fc777f6842fc93e1cefc3644e48d332a0d7c1520f53fd29fddb775

build:
  entry_points:
    - cacts = cacts:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - psutil
    - pyyaml

test:
  imports:
    - cacts
  commands:
    - pip check
    - cacts --help
    - cacts --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/E3SM-Project/cacts
  summary: A framework for configurable unit testing of a cmake-based project
  license: BSD-3-Clause
  license_file: license

extra:
  recipe-maintainers:
    - mahf708
    - bartgol
    - xylar
