schema_version: 1

context:
  name: cacts
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cacts-${{ version }}.tar.gz
  sha256: f01aeb42d14bdbef5eeee736484a8cc3024c1fc08752f76b74aad9c9ac80cd17

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cacts = cacts:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - psutil
    - pyyaml

tests:
  - python:
      imports:
        - cacts
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - cacts --help
      - cacts --version

about:
  summary: A framework for configurable unit testing of a cmake-based project
  license: BSD-3-Clause
  license_file: license
  homepage: https://github.com/E3SM-Project/cacts

extra:
  recipe-maintainers:
    - mahf708
    - bartgol
    - xylar
